#ifndef INCLUDE_ACQUISITIONPARAMETERS_H_
    #define INCLUDE_ACQUISITIONPARAMETERS_H_

    #define FORMAT_LEAP_IMAGE_WIDTH 640
    #define FORMAT_LEAP_IMAGE_HEIGHT 240
#endif // SHARED_ACQUISITIONPARAMETERS_H_
